# Generated by Django 5.0.3 on 2024-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('club', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
