# Generated by Django 5.0.3 on 2024-04-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='Registration_link',
            field=models.URLField(default='https://example.com'),
        ),
    ]
