# Generated by Django 5.0.3 on 2024-04-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventdetails_event_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='event_date_time',
        ),
    ]
