# Generated by Django 5.0.3 on 2024-04-09 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_eventdetails_event_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='event_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
