# Generated by Django 5.0.3 on 2024-04-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventdetails_event_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
