# Generated by Django 5.0.3 on 2024-04-09 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventdetails_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='event_date_time',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='event_name',
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
