# Generated by Django 5.0.3 on 2024-04-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_eventdetails_event_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='event_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
