# Generated by Django 5.0.3 on 2024-04-09 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_eventdetails_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='created_date',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='updated_date',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
