# Generated by Django 5.0.3 on 2024-04-09 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_eventdetails_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='updated_date1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
