# Generated by Django 5.0.3 on 2024-04-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_eventdetails_updated_date1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetails',
            old_name='updated_date',
            new_name='updated_time',
        ),
    ]
