# Generated by Django 5.0.3 on 2024-04-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_rename_updated_date_eventdetails_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
